/**
 * CID-10 — subconjunto curado dos códigos mais usados na atenção primária e
 * hospitalar brasileira (DATASUS). Não é a tabela completa (~14 mil códigos):
 * é o catálogo embutido para autocomplete offline-friendly; a carga completa
 * (arquivo oficial DATASUS) entra por seed/import em fase posterior.
 */
export interface Cid10 {
  codigo: string; // com ponto (ex.: "I10", "E11.9")
  descricao: string;
}

export const CID10: Cid10[] = [
  // Cap. I — Infecciosas e parasitárias
  { codigo: 'A00', descricao: 'Cólera' },
  { codigo: 'A01.0', descricao: 'Febre tifoide' },
  { codigo: 'A05.1', descricao: 'Botulismo' },
  { codigo: 'A09', descricao: 'Diarreia e gastroenterite de origem infecciosa presumível' },
  { codigo: 'A15', descricao: 'Tuberculose respiratória, com confirmação bacteriológica e histológica' },
  { codigo: 'A16', descricao: 'Tuberculose das vias respiratórias, sem confirmação' },
  { codigo: 'A20', descricao: 'Peste' },
  { codigo: 'A27', descricao: 'Leptospirose' },
  { codigo: 'A30', descricao: 'Hanseníase [doença de Hansen]' },
  { codigo: 'A33', descricao: 'Tétano do recém-nascido' },
  { codigo: 'A35', descricao: 'Outros tipos de tétano' },
  { codigo: 'A36', descricao: 'Difteria' },
  { codigo: 'A37', descricao: 'Coqueluche' },
  { codigo: 'A39', descricao: 'Infecção meningocócica' },
  { codigo: 'A46', descricao: 'Erisipela' },
  { codigo: 'A50', descricao: 'Sífilis congênita' },
  { codigo: 'A51', descricao: 'Sífilis precoce' },
  { codigo: 'A53', descricao: 'Outras formas e as não especificadas da sífilis' },
  { codigo: 'A80', descricao: 'Poliomielite aguda' },
  { codigo: 'A82', descricao: 'Raiva' },
  { codigo: 'A87', descricao: 'Meningite viral' },
  { codigo: 'A90', descricao: 'Dengue [dengue clássico]' },
  { codigo: 'A91', descricao: 'Febre hemorrágica devida ao vírus do dengue' },
  { codigo: 'A92.0', descricao: 'Febre de Chikungunya' },
  { codigo: 'A92.8', descricao: 'Outras febres virais especificadas transmitidas por mosquitos (Zika)' },
  { codigo: 'A95', descricao: 'Febre amarela' },
  { codigo: 'A98.5', descricao: 'Febre hemorrágica com síndrome renal (hantavirose)' },
  { codigo: 'B01', descricao: 'Varicela [catapora]' },
  { codigo: 'B04', descricao: 'Varíola dos macacos [mpox]' },
  { codigo: 'B05', descricao: 'Sarampo' },
  { codigo: 'B06', descricao: 'Rubéola' },
  { codigo: 'B15', descricao: 'Hepatite aguda A' },
  { codigo: 'B16', descricao: 'Hepatite aguda B' },
  { codigo: 'B17.1', descricao: 'Hepatite aguda C' },
  { codigo: 'B19', descricao: 'Hepatite viral não especificada' },
  { codigo: 'B20', descricao: 'Doença pelo HIV resultando em doenças infecciosas e parasitárias' },
  { codigo: 'B24', descricao: 'Doença pelo HIV não especificada' },
  { codigo: 'B34.9', descricao: 'Infecção viral não especificada' },
  { codigo: 'B50', descricao: 'Malária por Plasmodium falciparum' },
  { codigo: 'B51', descricao: 'Malária por Plasmodium vivax' },
  { codigo: 'B55.0', descricao: 'Leishmaniose visceral' },
  { codigo: 'B57.1', descricao: 'Doença de Chagas aguda sem comprometimento cardíaco' },
  { codigo: 'B58', descricao: 'Toxoplasmose' },
  { codigo: 'B86', descricao: 'Escabiose [sarna]' },
  // Cap. II — Neoplasias
  { codigo: 'C16', descricao: 'Neoplasia maligna do estômago' },
  { codigo: 'C18', descricao: 'Neoplasia maligna do cólon' },
  { codigo: 'C34', descricao: 'Neoplasia maligna dos brônquios e dos pulmões' },
  { codigo: 'C44', descricao: 'Outras neoplasias malignas da pele' },
  { codigo: 'C50', descricao: 'Neoplasia maligna da mama' },
  { codigo: 'C53', descricao: 'Neoplasia maligna do colo do útero' },
  { codigo: 'C61', descricao: 'Neoplasia maligna da próstata' },
  { codigo: 'C80', descricao: 'Neoplasia maligna, sem especificação de localização' },
  { codigo: 'D50', descricao: 'Anemia por deficiência de ferro' },
  // Cap. IV — Endócrinas, nutricionais e metabólicas
  { codigo: 'E03.9', descricao: 'Hipotireoidismo não especificado' },
  { codigo: 'E05', descricao: 'Tireotoxicose [hipertireoidismo]' },
  { codigo: 'E10', descricao: 'Diabetes mellitus insulino-dependente (tipo 1)' },
  { codigo: 'E11', descricao: 'Diabetes mellitus não-insulino-dependente (tipo 2)' },
  { codigo: 'E11.9', descricao: 'Diabetes mellitus tipo 2 sem complicações' },
  { codigo: 'E14', descricao: 'Diabetes mellitus não especificado' },
  { codigo: 'E46', descricao: 'Desnutrição proteico-calórica não especificada' },
  { codigo: 'E66', descricao: 'Obesidade' },
  { codigo: 'E78', descricao: 'Distúrbios do metabolismo de lipoproteínas (dislipidemia)' },
  { codigo: 'E86', descricao: 'Depleção de volume (desidratação)' },
  // Cap. V — Transtornos mentais
  { codigo: 'F10', descricao: 'Transtornos mentais devidos ao uso de álcool' },
  { codigo: 'F17', descricao: 'Transtornos mentais devidos ao uso de fumo' },
  { codigo: 'F20', descricao: 'Esquizofrenia' },
  { codigo: 'F29', descricao: 'Psicose não-orgânica não especificada' },
  { codigo: 'F32', descricao: 'Episódios depressivos' },
  { codigo: 'F33', descricao: 'Transtorno depressivo recorrente' },
  { codigo: 'F41', descricao: 'Outros transtornos ansiosos' },
  { codigo: 'F41.1', descricao: 'Ansiedade generalizada' },
  // Cap. VI — Sistema nervoso
  { codigo: 'G00', descricao: 'Meningite bacteriana não classificada em outra parte' },
  { codigo: 'G40', descricao: 'Epilepsia' },
  { codigo: 'G43', descricao: 'Enxaqueca' },
  { codigo: 'G45', descricao: 'Acidentes vasculares cerebrais isquêmicos transitórios' },
  // Cap. VII/VIII — Olho e ouvido
  { codigo: 'H10', descricao: 'Conjuntivite' },
  { codigo: 'H66', descricao: 'Otite média supurativa e as não especificadas' },
  // Cap. IX — Aparelho circulatório
  { codigo: 'I10', descricao: 'Hipertensão essencial (primária)' },
  { codigo: 'I11', descricao: 'Doença cardíaca hipertensiva' },
  { codigo: 'I20', descricao: 'Angina pectoris' },
  { codigo: 'I20.0', descricao: 'Angina instável' },
  { codigo: 'I21', descricao: 'Infarto agudo do miocárdio' },
  { codigo: 'I48', descricao: 'Flutter e fibrilação atrial' },
  { codigo: 'I50', descricao: 'Insuficiência cardíaca' },
  { codigo: 'I63', descricao: 'Infarto cerebral' },
  { codigo: 'I64', descricao: 'Acidente vascular cerebral não especificado' },
  { codigo: 'I80', descricao: 'Flebite e tromboflebite' },
  { codigo: 'I84', descricao: 'Hemorroidas' },
  // Cap. X — Aparelho respiratório
  { codigo: 'J00', descricao: 'Nasofaringite aguda [resfriado comum]' },
  { codigo: 'J02', descricao: 'Faringite aguda' },
  { codigo: 'J03', descricao: 'Amigdalite aguda' },
  { codigo: 'J06', descricao: 'Infecções agudas das vias aéreas superiores' },
  { codigo: 'J11', descricao: 'Influenza [gripe] devida a vírus não identificado' },
  { codigo: 'J15', descricao: 'Pneumonia bacteriana não classificada em outra parte' },
  { codigo: 'J18', descricao: 'Pneumonia por microorganismo não especificado' },
  { codigo: 'J20', descricao: 'Bronquite aguda' },
  { codigo: 'J44', descricao: 'Doença pulmonar obstrutiva crônica (DPOC)' },
  { codigo: 'J45', descricao: 'Asma' },
  { codigo: 'J81', descricao: 'Edema pulmonar' },
  // Cap. XI — Aparelho digestivo
  { codigo: 'K02', descricao: 'Cárie dentária' },
  { codigo: 'K29', descricao: 'Gastrite e duodenite' },
  { codigo: 'K35', descricao: 'Apendicite aguda' },
  { codigo: 'K40', descricao: 'Hérnia inguinal' },
  { codigo: 'K80', descricao: 'Colelitíase [cálculo biliar]' },
  { codigo: 'K92.2', descricao: 'Hemorragia gastrointestinal, sem outra especificação' },
  // Cap. XII/XIII — Pele e osteomuscular
  { codigo: 'L03', descricao: 'Celulite (infecção de pele)' },
  { codigo: 'M17', descricao: 'Gonartrose [artrose do joelho]' },
  { codigo: 'M25.5', descricao: 'Dor articular' },
  { codigo: 'M54', descricao: 'Dorsalgia' },
  { codigo: 'M54.5', descricao: 'Dor lombar baixa (lombalgia)' },
  { codigo: 'M79.1', descricao: 'Mialgia' },
  // Cap. XIV — Aparelho geniturinário
  { codigo: 'N18', descricao: 'Insuficiência renal crônica' },
  { codigo: 'N20', descricao: 'Calculose do rim e do ureter' },
  { codigo: 'N30', descricao: 'Cistite' },
  { codigo: 'N39.0', descricao: 'Infecção do trato urinário de localização não especificada' },
  // Cap. XV — Gravidez, parto e puerpério
  { codigo: 'O14', descricao: 'Pré-eclâmpsia' },
  { codigo: 'O20.0', descricao: 'Ameaça de aborto' },
  { codigo: 'O23', descricao: 'Infecções do trato geniturinário na gravidez' },
  { codigo: 'O80', descricao: 'Parto único espontâneo' },
  { codigo: 'O82', descricao: 'Parto único por cesariana' },
  // Cap. XVI/XVII — Perinatal e malformações
  { codigo: 'P07', descricao: 'Transtornos relacionados à gestação curta e peso baixo ao nascer' },
  { codigo: 'P59', descricao: 'Icterícia neonatal' },
  { codigo: 'Q21', descricao: 'Malformações congênitas dos septos cardíacos' },
  // Cap. XVIII — Sintomas e sinais
  { codigo: 'R05', descricao: 'Tosse' },
  { codigo: 'R06.0', descricao: 'Dispneia' },
  { codigo: 'R10', descricao: 'Dor abdominal e pélvica' },
  { codigo: 'R10.4', descricao: 'Outras dores abdominais e as não especificadas' },
  { codigo: 'R11', descricao: 'Náusea e vômitos' },
  { codigo: 'R50', descricao: 'Febre de origem desconhecida' },
  { codigo: 'R51', descricao: 'Cefaleia' },
  { codigo: 'R55', descricao: 'Síncope e colapso' },
  { codigo: 'R57.0', descricao: 'Choque cardiogênico' },
  { codigo: 'R57.1', descricao: 'Choque hipovolêmico' },
  // Cap. XIX/XX — Lesões e causas externas
  { codigo: 'S06', descricao: 'Traumatismo intracraniano' },
  { codigo: 'S42', descricao: 'Fratura do ombro e do braço' },
  { codigo: 'S52', descricao: 'Fratura do antebraço' },
  { codigo: 'S72', descricao: 'Fratura do fêmur' },
  { codigo: 'S82', descricao: 'Fratura da perna, incluindo tornozelo' },
  { codigo: 'T14.1', descricao: 'Ferimento aberto de região não especificada do corpo' },
  { codigo: 'T63', descricao: 'Efeito tóxico de contato com animais venenosos' },
  { codigo: 'T78.4', descricao: 'Alergia não especificada' },
  { codigo: 'X20', descricao: 'Contato com serpentes e lagartos venenosos' },
  { codigo: 'X23', descricao: 'Contato com abelhas, vespas e vespões' },
  { codigo: 'X27', descricao: 'Contato com outros animais venenosos especificados' },
  // Cap. XXI/XXII — Fatores que influenciam o estado de saúde / especiais
  { codigo: 'U07.1', descricao: 'COVID-19, vírus identificado' },
  { codigo: 'U07.2', descricao: 'COVID-19, vírus não identificado' },
  { codigo: 'U06.9', descricao: 'Doença pelo vírus Zika, não especificada' },
  { codigo: 'Z00.0', descricao: 'Exame médico geral' },
  { codigo: 'Z21', descricao: 'Estado de infecção assintomática pelo HIV' },
  { codigo: 'Z34', descricao: 'Supervisão de gravidez normal' },
  { codigo: 'Z38', descricao: 'Nascidos vivos segundo o local de nascimento' },
];
